---
title: "Jacob Wittman's Resume"
author: Jacob Wittman
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['resume.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
library(stringr)
library(dplyr)
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  pdf_mode = params$pdf_mode,
  short_description = FALSE,
  data_location = "data/" 
 
)

# Remove the dashes from the article entries so author names aren't bullet pointed
# Also we're going to group teaching experience with projects and just call it 
# all experience
CV$entries_data <- CV$entries_data %>%
  mutate(section = case_when(section == 'teaching_positions' ~ 'projects',
                        TRUE ~ section)) %>% 
  mutate(section = case_when(secondary_section == 'experience' ~ 'experience',
                            TRUE ~ section)) %>% 
  filter(in_resume == TRUE)


# Edit some of the entries for the resume
# CV$entries_data <- CV$entries_data %>% 
#   mutate(description_bullets = case_when(section == 'teaching_positions' & title != 'Guest Lecturer' ~ "",
#                                          section == 'grants_honors_awards'  ~ "",
#                                          TRUE ~ description_bullets))

```

<!-- not very elegant solution for using academicons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r introduction}
# Note the special double pipe so we modify the CV object in place
# CV %<>% print_text_block("intro") 
```


```{r view-online, include = FALSE}
if(params$pdf_mode){
  cat("")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/wittja01/cv2/blob/main/cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r contact}
CV %>% print_contact_info()
```



Skills {#skills}
--------------------------------------------------------------------------------

```{r language-skills}
CV %>% print_skill_bars()
```


Main
================================================================================

Jacob Wittman {#title}
--------------------------------------------------------------------------------


Experience {data-icon=laptop data-concise=true}
--------------------------------------------------------------------------------

```{r projects}
CV %<>% print_section('experience')
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
::: aside

```{r publications-aside}
CV %<>% print_text_block('short_resume_pubs')
```
:::

```{r education}
CV %<>% print_section('education')
```

::: aside

<br>

<br>


Made with the R packages [**pagedown**](https://github.com/rstudio/pagedown) and [**datadrivencv**](https://github.com/nstrayer/datadrivencv).

Last updated on `r Sys.Date()`.
:::


